#!/bin/sh

# parameter 1 contains the path to the commit message file

LIMIT=72

MESSAGE=$(cat "$1" | rg -v '^#')

if ! echo "$MESSAGE" | rg -q --multiline "\\A.{1,$LIMIT}\\n(\\n|\\z)"; then
    echo "$MESSAGE" > /tmp/badcommit
    echo "Error: summary line longer than $LIMIT characters or missing empty line after summary line" >&2
    echo "bad commit message written to /tmp/badcommit" >&2
    exit 1
fi

echo "$MESSAGE" | fmt -w $LIMIT > "$1"
rm -f /tmp/badcommit # /tmp/badcommit must be removed so that later commits don't use it as a message template
